### ISSUE TITLE
Separate out persistence

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/system_registry#13]
This is a placeholder for discussion on whether or not to include persistence in "1.0". Here's my understanding of the pros/cons:

Pros:
1. The current persistence implementation is a pretty small piece of code so doesn't add much bloat.
2. One less project for people to depend on

Cons:
1. Not a core feature for a module that's primarily a kv store with update notifications
2. Implementation is simplistic. If you're using sqlite or any other persistence library on your device already, it's annoying to have data persisted in two different ways.

I'm leaning towards pulling persistence out for "1.0" so that we can concentrate on docs, usage examples, best practices, etc. of the core features of system_registry. It's not that the code size for persistence is that large, but it has implications on software architecture that probably warrant more discussion before 1.0.

**Comment by GregMefford** [comment]
I agree that, if we include some kind of persistence for configuration, we should have a pluggable way to choose a different back-end protocol (e.g. like `Logger` only includes simple back-ends but supports third-party ones). One argument to include something basic is that the [`Config` processor](https://github.com/nerves-project/system_registry/blob/master/lib/system_registry/processor/config.ex) is included by default and it would be a _lot_ more useful in practice if there were some kind of persistence system available for a 1.0 release, since we know we definitely want to have that eventually.
